app:
  build: .
  command: python -u app_1.py
  ports:
    - "5000:5000"
  volumes:
    - .:/app_1
  links:
    - db
db:
  image: mongo:latest
  hostname: notes_mongodb
  environment:
    - MONGO_INITDB_DATABASE=notesDB
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=pass
  volumes:
    - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
  ports:
    - 27017:27017